In [4]:
import numpy as np
import matplotlib.pylab as plt

x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x.T @ A @ x

228

In [13]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [18]:
B = (np.arange(9) -4).reshape((3,3))
B

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [21]:
np.linalg.norm(B)

7.745966692414834

In [26]:
np.trace(np.eye(3))

3.0

In [49]:
np.trace(np.eye(3))


3.0

In [51]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(C)

-9.51619735392994e-16

In [56]:
D = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
d = np.arange(1,4)
np.dot(np.dot(d,D),d.T)

12

In [58]:
np.trace(D)

6

In [75]:
np.linalg.det(D)

4.0

In [76]:
E = np.array([[1,2],[3,4]])
e = np.arange(1,3)
np.dot(np.dot(e,E),e.T)


27

In [78]:
np.trace(E)

5

In [79]:
np.linalg.det(E)

-2.0000000000000004

In [85]:
F = 1/(13**1/2)*np.array([[3,-1],[2,1]])
Finv = np.linalg.inv(F)
Finv

array([[ 1.3,  1.3],
       [-2.6,  3.9]])

In [87]:
G = np.array([[1,1,0],[0,1,1],[1,1,1]])
Ginv = np.linalg.inv(G)
Ginv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])